# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "hubotserver" do |hubotserver|
    hubotserver.vm.box = "jptoto/Windows2012R2"
    hubotserver.vm.hostname = "win-web01"
    hubotserver.vm.communicator = :winrm
    hubotserver.winrm.username = "vagrant"
    hubotserver.winrm.password = "vagrant"
    hubotserver.vm.network "private_network", ip: "172.28.128.100"
    hubotserver.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    # config.vm.provision :shell do |shell|
    #   shell.path = "https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"
    # end
    hubotserver.vm.provision "file", source: "demo1.ps1", destination: "C:\\demo\\demo1.ps1"
    hubotserver.vm.provision :shell, inline: "
    if ($PSVersionTable.PSVersion.Major -eq 4)
    {
      choco install powershell 5 -y
    }
    "
  end

  config.vm.define "win2012r2" do |win2012r2|
    # web01.vm.box = "mwrock/Windows2016"
    win2012r2.vm.box = "jptoto/Windows2012R2"
    win2012r2.vm.hostname = "win-web01"
    win2012r2.vm.communicator = :winrm
    win2012r2.winrm.username = "vagrant"
    win2012r2.winrm.password = "vagrant"
    win2012r2.vm.network "private_network", ip: "172.28.128.101"
    win2012r2.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    # config.vm.provision :shell do |shell|
    #   shell.path = "https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"
    # end
    config.vm.provision :shell, inline: "
    if ($PSVersionTable.PSVersion.Major -eq 4)
    {
      choco install powershell 5 -y
    }
    "
  end
end

# ansible web -i ~/ansibleconfig/inventory.yml -m win_ping
