# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "hubotserver" do |hubotserver|
    hubotserver.vm.box = "jptoto/Windows2012R2"
    hubotserver.vm.hostname = "hubotserver"
    hubotserver.vm.communicator = :winrm
    hubotserver.winrm.username = "vagrant"
    hubotserver.winrm.password = "vagrant"
    hubotserver.vm.network "private_network", ip: "172.28.128.100"
    hubotserver.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.gui = true
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
    end
    hubotserver.vm.provision "shell", path: "provision/generic.ps1"
    hubotserver.vm.provision "shell", path: "provision/hubot.ps1"
  end

  config.vm.define "win2012r2" do |win2012r2|
    win2012r2.vm.box = "jptoto/Windows2012R2"
    win2012r2.vm.hostname = "win2012r2"
    win2012r2.vm.communicator = :winrm
    win2012r2.winrm.username = "vagrant"
    win2012r2.winrm.password = "vagrant"
    win2012r2.vm.network "private_network", ip: "172.28.128.101"
    win2012r2.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.gui = true
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    end
    win2012r2.vm.provision "shell", path: "provision/generic.ps1"
  end
end
