Vagrant.configure("2") do |config|
  config.vm.box = "jptoto/Windows2012R2"
  config.vm.hostname = "win2012ssh"
  config.vm.network "private_network", ip: "172.28.128.200"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end
  config.vm.communicator = :winrm
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"
  config.vm.provision "shell", path: "install_ssh.ps1"
  config.vm.provision "file", source: "./ssh_config/ssh_config", destination: "C:\\Program Files\\OpenSSH-Win64\\sshd_config"
  config.vm.provision "file", source: "./authorized_keys/authorized_keys", destination: "C:\\Users\\vagrant\\.ssh\\authorized_keys"

  # config.vm.provision :shell, inline: "
  #   ntrights.exe -u 'NT SERVICE\\SSHD' +r SeAssignPrimaryTokenPrivilege
  # "

  # trigger reload
  # config.vm.provision :reload
end

##############
# Connecting #
##############
## Add ssh key so you don't get prompted

# ssh-keyscan -H 172.28.128.13 >> ~/.ssh/known_hosts

# powershell
# Enter-PSSession -HostName 172.28.128.13 -UserName vagrant -KeyPath /Users/Matthew/.ssh/powershell_win2012

# $s = New-PSSession -HostName 172.28.128.13 -UserName vagrant -KeyPath /Users/Matthew/.ssh/powershell_win2012
# Invoke-Command -Session $s -ScriptBlock { Get-ChildItem C:\temp }
